# Use an official Ubuntu runtime as a parent image
FROM ubuntu:latest

# Set the working directory to /app
WORKDIR /app

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg

# Copy the current directory contents into the container at /app
COPY . /app

# Define environment variable
ENV NAME World

# Run the command to start your application
CMD ["bash"]
